FROM ubuntu:22.04

RUN apt-get update && apt-get -y dist-upgrade ; \
    apt-get -y install --no-install-recommends galera-arbitrator-4 ; \
    rm -rf /var/lib/apt/lists/*

EXPOSE 4567

ENTRYPOINT ["/usr/bin/garbd","-c","/data/garb.cfg"]